name: docker-build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker images
        run: |
          docker-compose -f deployment/docker-compose.build.prod.yml build --build-arg VITE_REACT_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          docker-compose -f deployment/docker-compose.build.prod.yml push
